version: '3.4'

services:
  onecalc.webapi:
    image: ${DOCKER_REGISTRY-}onecalcwebapi
    build:
      context: .
      dockerfile: OneCalc.WebApi/Dockerfile

  postgres:
    container_name: calc_one_postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-example}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5464:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: calc_one_pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5074}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
