version: '3.4'

services:
  onecalc.webapi:
    image: ${DOCKER_REGISTRY-}onecalcwebapi
    build:
      context: .
      dockerfile: OneCalc.WebApi/Dockerfile
    networks:
      - postgres
    restart: unless-stopped

  postgres:
    container_name: calc_one_postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-example}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5464:5432"
    networks:
      - postgres
    restart: unless-stopped
  
networks:
  postgres:
    driver: bridge

volumes:
    postgres: