version: '3.5'
services:
  postgres:
    container_name: calc_one_postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-example}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5464:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: calc_one_pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5074}:80"
    networks:
      - postgres
    restart: unless-stopped

  crowdsale.webui:
    container_name: calc_one_webapi_container
    build:
      context: .
      dockerfile: Crowdsale.WebUI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44386
    ports:
      - "59854:80"
      - "44386:443"
      - "5432"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
   

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
